#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"

rand_hex() {
  local bytes="${1:-48}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi
  local value=""
  while [ "${#value}" -lt "$((bytes * 2))" ]; do
    value="${value}$(od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n')"
  done
  printf '%s\n' "${value:0:$((bytes * 2))}"
}

rand_password() {
  local length="${1:-24}"
  local value=""
  while [ "${#value}" -lt "$length" ]; do
    if command -v openssl >/dev/null 2>&1; then
      value="${value}$(openssl rand -base64 "$length" | LC_ALL=C tr -dc 'A-Za-z0-9')"
    else
      value="${value}$(dd if=/dev/urandom bs=256 count=1 2>/dev/null | LC_ALL=C tr -dc 'A-Za-z0-9')"
    fi
  done
  printf '%s\n' "${value:0:$length}"
}

has_env_key() {
  local key="$1"
  [ -f "$ENV_FILE" ] && grep -Eq "^[[:space:]]*${key}=" "$ENV_FILE"
}

append_env() {
  local key="$1"
  local value="$2"

  if has_env_key "$key"; then
    return
  fi

  printf '%s=%s\n' "$key" "$value" >>"$ENV_FILE"
}

env_value() {
  local key="$1"
  awk -F= -v key="$key" '
    $1 == key {
      value = substr($0, length(key) + 2)
      gsub(/^["'\'']|["'\'']$/, "", value)
      print value
      exit
    }
  ' "$ENV_FILE"
}

mkdir -p "$(dirname "$ENV_FILE")"
if [ ! -f "$ENV_FILE" ]; then
  {
    printf '# Cedar Discipleship deployment environment\n'
    printf '# Generated by scripts/init-deploy-env.sh. Keep this file out of git.\n'
  } >"$ENV_FILE"
fi

append_env COMPOSE_PROJECT_NAME cedar
append_env AGP_CONTAINER_PREFIX cedar
append_env AGP_WEB_PORT 5114
append_env AGP_MYSQL_PORT 3307
append_env AGP_DATA_DIR /volume2/docker/cedar-discipleship-data
append_env AGP_LOG_DIR "$ROOT_DIR/logs"

append_env MYSQL_DATABASE agp
append_env MYSQL_USER agp
append_env MYSQL_LOWER_CASE_TABLE_NAMES 0
append_env MYSQL_PASSWORD "$(rand_password 24)"
append_env MYSQL_ROOT_PASSWORD "$(rand_password 32)"

append_env AGP_JWT_SECRET "$(rand_hex 48)"
append_env AGP_TOKEN_TTL ""
append_env AGP_RESOURCE_ROOT "$(env_value AGP_DATA_DIR)/resources"
append_env BOOTSTRAP_SUPERADMIN_USERNAME admin
append_env BOOTSTRAP_SUPERADMIN_PASSWORD "$(rand_password 20)"
append_env BOOTSTRAP_SUPERADMIN_DISPLAY_NAME "超级管理员"

append_env GOPROXY "https://goproxy.cn,direct"
append_env NPM_CONFIG_REGISTRY "https://registry.npmmirror.com"

AGP_DATA_DIR_VALUE="$(env_value AGP_DATA_DIR)"
AGP_LOG_DIR_VALUE="$(env_value AGP_LOG_DIR)"
AGP_RESOURCE_ROOT_VALUE="$(env_value AGP_RESOURCE_ROOT)"
mkdir -p \
  "$AGP_DATA_DIR_VALUE/mysql" \
  "$AGP_RESOURCE_ROOT_VALUE" \
  "$AGP_DATA_DIR_VALUE/backups/mysql" \
  "$AGP_LOG_DIR_VALUE/backend" \
  "$AGP_LOG_DIR_VALUE/frontend" \
  "$AGP_LOG_DIR_VALUE/mysql"

chmod 600 "$ENV_FILE" 2>/dev/null || true

cat <<EOF
部署环境变量已写入: $ENV_FILE
部署数据目录已创建: $AGP_DATA_DIR_VALUE
日志目录已创建: $AGP_LOG_DIR_VALUE

启动命令:
  docker compose --env-file "$ENV_FILE" -f deploy/docker-compose.separated.yml up -d --build

查看当前配置:
  docker compose --env-file "$ENV_FILE" -f deploy/docker-compose.separated.yml config
EOF
